#!/bin/bash

cd `dirname $0`
SCRIPTDIR=`pwd`
cd -

export DISPLAY=:0

CP="$SCRIPTDIR:$SCRIPTDIR/config:$SCRIPTDIR/lib/*"

java -Xms256m -Xmx256m \
     -Djava.awt.headless=false \
     -Dcom.sun.management.jmxremote \
     -Dcom.sun.management.jmxremote.port=9010 \
     -Dcom.sun.management.jmxremote.local.only=false \
     -Dcom.sun.management.jmxremote.authenticate=false \
     -Dcom.sun.management.jmxremote.ssl=false \
     -Djava.rmi.server.hostname=127.0.0.1 \
     -Dlogging.config=/Users/sandeep/softwares/bin/sconsole/config/logback.xml \
     -classpath $CP com.sandy.sconsole.SConsole
